"""
Django settings for backend config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from decouple import config

from .db_url import parse_postgres_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
CLAUDE_API_KEY = config('CLAUDE_API_KEY')
ANTHROPIC_MODEL = config('ANTHROPIC_MODEL', default='claude-3-5-sonnet-20241022')
OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default='')
OPENROUTER_MODEL = config('OPENROUTER_MODEL', default='openrouter/free')
OPENROUTER_API_URL = config(
    'OPENROUTER_API_URL',
    default='https://openrouter.ai/api/v1/chat/completions',
)
PLANT_DETECTION_API_KEY = config('PLANT_DETECTION_API_KEY')
PLANT_API_URL = config('PLANT_API_URL', default='https://api.plant.id/v3')

# Kindwise crop API (legacy `core` routes only — not used by `/api/scan` or `/api/confirm`).
PLANTHEALTH_API_KEY = config('PLANTHEALTH_API_KEY', default='')
PLANTHEALTH_API_URL = config(
    'PLANTHEALTH_API_URL',
    default='https://crop.kindwise.com/api/v1',
)
# Names expected by `core/services/kindwise.py` crop_identification()
CROP_API_URL = PLANTHEALTH_API_URL
PLANT_HEALTH_API_KEY = PLANTHEALTH_API_KEY

# Google Gemini (legacy `core` crop advice — `gemini_crop.py`)
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-3-flash-preview')
GEMINI_API_METHOD = config('GEMINI_API_METHOD', default='streamGenerateContent')
GEMINI_THINKING_LEVEL = config('GEMINI_THINKING_LEVEL', default='HIGH')
GEMINI_USE_GOOGLE_SEARCH = config('GEMINI_USE_GOOGLE_SEARCH', default=True, cast=bool)

# Optional: Khaya / Lelapa (translation of diagnosis + locale tooling)
KHAYA_API_TOKEN = config('KHAYA_API_TOKEN', default='')
KHAYA_TRANSLATE_URL = config(
    'KHAYA_TRANSLATE_URL',
    default='https://api.lelapa.ai/v1/translate/process',
)

# Ghana NLP translation (preferred if API_URL + PRIMARY/SECONDARY key are configured)
API_URL = config('API_URL', default='https://translation-api.ghananlp.org/v1/translate')
API_SUPPORTED_LANGUAGES_URL = config(
    'API_SUPPORTED_LANGUAGES_URL',
    default='https://translation-api.ghananlp.org/v1/languages',
)
PRIMARY_API_KEY = config('PRIMARY_API_KEY', default='')
SECONDARY_API_KEY = config('SECONDARY_API_KEY', default='')


def _sync_integration_env() -> None:
    """Match legacy integration: expose keys under names some tooling expects in os.environ."""
    if not os.environ.get('PLANT_ID_API_KEY'):
        v = (PLANT_DETECTION_API_KEY or '').strip() if PLANT_DETECTION_API_KEY else ''
        if v:
            os.environ['PLANT_ID_API_KEY'] = v
    if not os.environ.get('ANTHROPIC_API_KEY'):
        v = (CLAUDE_API_KEY or '').strip() if CLAUDE_API_KEY else ''
        if v:
            os.environ['ANTHROPIC_API_KEY'] = v
    if not os.environ.get('KHAYA_API_TOKEN'):
        v = (KHAYA_API_TOKEN or '').strip() if KHAYA_API_TOKEN else ''
        if v:
            os.environ['KHAYA_API_TOKEN'] = v


_sync_integration_env()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [
    h.strip()
    for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
    if h.strip()
]

_csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in _csrf_origins.split(',') if o.strip()
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = config('DATABASE_URL', default='')
if _database_url:
    DATABASES = {
        'default': parse_postgres_url(_database_url, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# SPA (Vite) on another origin — comma-separated in .env, or defaults below.
_cors_origins = config('CORS_ALLOWED_ORIGINS', default='')
if _cors_origins.strip():
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in _cors_origins.split(',') if o.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]

CORS_ALLOW_CREDENTIALS = True

SPECTACULAR_SETTINGS = {
    'TITLE': 'AgroSense API',
    'DESCRIPTION': 'Plant and crop identification plus plant health assessment via Kindwise / plant.id proxies.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

LOG_LEVEL = config('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'short': {
            '()': 'config.log_formatters.TruncatingConsoleFormatter',
            'format': '[%(levelname)s] %(asctime)s %(name)s: %(message)s',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'short',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
